language: node_js
node_js:
- '14'
script:
- npm test
- npm run build
deploy:
  on:
    branch: main
  provider: heroku
  app: cicd-project-gustavo
  api_key:
    secure: bT8qp901xB0GEuWMQEWV1qpyZV71rClL95fWTCYei2uaRq8yZV+ugvyT5LFNDtwhusCMZZjZY7cf4yHXA3m61idVTsNfN9R/oMu7on2i+2H3FBfYMF6XPBc0cgDwpeii/f+s8h0m14RftFaGDhJ8Kf4oxRR2143T7oig6e7fVQGty5LooWao+/uRBlrB2h5pf+knrEIO5OYkOgDjzqr4I/4nbdCYPn+Q0DLUDvH7zJFTnXMGPYxTyC8Jc3XF1W8m+dEnCJAlrD9PLrmSFitFlISnyUfxONTjxqsdkj3pIGzA4EqcLisyb+aPbqDlWPMB98EnBz5y0KQjDYaOPJ/Kc4GWIrMKZNE3ZDqyBtzGjCLx05EKd9a9V4KIWybYf4SaJbhw69mqmw8IVpgSWYgcZiqxbjyHNvGzuaYo0CrGrEVjOJzGeOjEB8PiqJXHBwwDhVvxEYd6lnA/sWkUIyjMd6UBGAogv8jvNm1MURQKtGRahltPpflKeWw3sZmtD9EhZMUMpqHTNT93yyu93C/nEqGmie7UckwPugEEch9/94f4723jwfP0oE3J4er2+ajoMqaVLEgU6piSWqhZCCeOGxygaG+V3F21ep3LFFuOhNM1CyuLeke89ZNVmRZa6f9QtKmiWmnvbg2HYmp33IPx1V1MoeYTzal5wTaWq/SJMR0=
