language: node_js
node_js:
- '14'
script:
- npm test
- npm run build
deploy:
  on:
    branch: main
  provider: heroku
  app: cicd-project-gustavo
  api_key:
    secure: Fb/OYn3ByUKRY3GSWcMddJKvFD0rQwYgg11vZ9vbR98CnMQOztn0Df7bVtGiqg5vcudQfUJSDAKCyWd4ppSYRQ/aeGlFxY3koIggEl1mZTd2+ANxtp6C/8155K5wY1VnqDRxij4s686EUv3brYUswTYjJVjI3Q/CtDeq1FEplYwFS3VxYcOs4f/H/1yt/AKV0BtSt6zKwSaNW7URu5s0Bs2clVWgRq/Qf+OCXwi3x9qVYhO6MBlPIu2nzeI9J6zY2jA/Sft64gubdV3aDXBNQA8ICSJqMDh/SDGKcTmjsyG7rParssll25Xb+OqDgG/GDFxYulIALstmRZJJEf/R7wEWDSmYImchjZyeiWbTOTf49j59/M0H0MhUxQWLc+bQ4PGZ6fINavnMt4u1TikL9huHptWSbvXA/djEQW2PzS5oPhS9oJPKMww3M56oOjId488SairtFIbzhY5tlDw7qjXcz8fEf+S+jLildqCDdhYkr+IHOitAMGYGfmTOurMH9Ce+LZFFA0J7W4oZJZPb28VvCoxuuWNo+FBQbIQqB+IrZK1G+tCVsMUlMZmo9AGTZijRYtVmSRB3QR06FyboT9Z9jN9qOV0UcSwowYlwJ0g12k8veZkMYHJbaNwKtE3FzYS5xFmw2awGu7kzuimrCMvLGr0aOljk59CaK3zXVW0=
notifications:
  slack: isutn2021:23jgA19ln0hF2sUoVMUs8ITQ